#!/bin/sh
. "$(dirname "$0")/_/husky.sh"


echo "🔬🔬 Gnosis is validating your commit..."

npm run validate || (
    echo "🔥🔥 Failed to commit!!! 🔥🔥
🔥🔥 Please fix all type-related, linting and formating issues ASAP!!! 🔥🔥
💡💡 You can run 'npm run eslint:fix' to let ESlint auto-correct the linting errors... 💡💡
💡💡 You can run 'npm run prettier:format' to let Prettier auto-format all the files... 💡💡"
    
    false; 
)

echo "👍💯 Commit approved!!! 💯👍"
